kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: "{{.Values.api.appName}}"
spec:
  replicas: {{ default 1 .Values.api.replicas }}
  template: 
    metadata:
      labels:
        app: "{{.Values.api.appName}}"
        version: "{{.Values.api.versionLabel}}"
    spec:
      containers:
      - name: "{{.Values.api.appName}}"
        image: "{{.Values.api.image}}:{{.Values.api.imageTag}}"
        imagePullPolicy: "{{.Values.api.imagePullPolicy}}"
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: "{{.Values.api.imagePullSecret}}"
---
kind: Service
apiVersion: v1
metadata:
  name: "{{.Values.api.appName}}"
  labels:
    app: "{{.Values.api.appName}}"
spec:
  selector:
    app: "{{.Values.api.appName}}"
  type: ClusterIP  
  ports:
  - name: http
    port: 8081
    targetPort: 8081