kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: web
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: web
        version: fault
    spec:
      containers:
      - name: web
        image: briarprivate.azurecr.io/chzbrgr71/smackweb:master-c399f02
        imagePullPolicy: Always
        env:
        - name: API_SERVICE
          value: api.default.svc.cluster.local
        - name: API_PORT
          value: "8081"
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acrregistrykey
---
kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  selector:
    app: web
  type: LoadBalancer  
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: api1
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        app: api
        version: v1
    spec:
      containers:
      - name: api
        image: briarprivate.azurecr.io/chzbrgr71/smackapi:staging-a01cbc0
        imagePullPolicy: Always
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: acrregistrykey
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: api2
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        app: api
        version: v2
    spec:
      containers:
      - name: api
        image: briarprivate.azurecr.io/chzbrgr71/smackapi:staging-a01cbc0
        imagePullPolicy: Always
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: acrregistrykey
---
kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  selector:
    app: api
  type: ClusterIP  
  ports:
  - name: http
    port: 8081
    targetPort: 8081