kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: smackweb
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: smackweb
        version: v1
    spec:
      containers:
      - name: smackweb
        image: chzbrgr71/smackweb:v1
        env:
        - name: API_SERVICE
          value: "smackapi.default.svc.cluster.local"
        - name: API_PORT
          value: "8081"
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: smackapi-v1
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        app: smackapi
        version: v1
    spec:
      containers:
      - name: smackapi
        image: chzbrgr71/smackapi:v1
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8081
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: smackapi-v2
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        app: smackapi
        version: v2
    spec:
      containers:
      - name: smackapi
        image: chzbrgr71/smackapi:v2
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: smackweb
spec:
  selector:
    app: smackweb
  type: LoadBalancer  
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: smackapi
spec:
  selector:
    app: smackapi
  type: ClusterIP  
  ports:
  - name: http
    port: 8081
    targetPort: 8081