apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: fault
spec:
  destination:
    name: api
  precedence: 50
  route:
  - labels:
      version: v1
    weight: 0
  - labels:
      version: v2
    weight: 100