apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: fault2
spec:
  destination:
    name: api.default.svc.cluster.local
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 0
  - labels:
      version: v2
    weight: 100