apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: api-fault
spec:
  destination:
    name: smackapi
  route:
  - labels:
      version: v1
  httpFault:
    delay:
      percent: 100   
      fixedDelay: 500ms