kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: "{{.Release.Name}}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.component}}"
spec:
  replicas: {{ default 1 .Values.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{.Release.Name}}-{{.Values.component}}"
  template: 
    metadata:
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: "{{.Release.Name}}-{{.Values.component}}"
    spec:
      imagePullSecrets:
        - name: acrregistrykey
      containers:
        - name: {{ template "fullname" . }}
          image: "{{.Values.image}}:{{.Values.imageTag}}"
          imagePullPolicy: "{{.Values.imagePullPolicy}}"
          ports:
          - name: http
            containerPort: {{.Values.containerPort}}
          env:
          - name: API_SERVICE
            value: "{{ .Values.apiService }}"
          - name: API_PORT
            value: "{{ .Values.apiPort }}"
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: KUBE_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBE_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          livenessProbe:
            httpGet:
              path: /test
              port: http
          readinessProbe:
            httpGet:
              path: /test
              port: http
---
kind: Service
apiVersion: v1
metadata:
  name: "{{.Release.Name}}-svc"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.component}}"
spec:
  selector:
    component: "{{.Release.Name}}-{{.Values.component}}"
  type: {{ default "ClusterIP" .Values.serviceType | quote }}  
  ports:
  - name: http
    port: {{.Values.servicePort}}
    targetPort: {{.Values.containerPort}}